apiVersion: v1
kind: Service
metadata:
  name: example-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
spec:
  selector:
    batch: c38
  ports:
    - port: 80
      targetPort: 8081
  type: LoadBalancer