datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      url: http://my-prometheus-server.default.svc.cluster.local
      access: proxy
      isDefault: true
service:
  enabled: true
  type: LoadBalancer
  port: 80
  targetPort: 3000